# Generated by Django 4.0.4 on 2022-04-28 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personality', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('google_profile_url', models.URLField(blank=True, null=True, verbose_name='Google Profile URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('current_personality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_persoanlity', to='personality.personality', verbose_name='Personality')),
                ('liked_artists', models.ManyToManyField(to='music.artist', verbose_name='Liked Artists')),
                ('liked_songs', models.ManyToManyField(to='music.song', verbose_name='Liked Songs')),
                ('search_history', models.ManyToManyField(related_name='persoanlity_history', to='personality.personality', verbose_name='Personality History')),
                ('suggested_songs', models.ManyToManyField(to='music.suggestedsongs', verbose_name='Suggested Songs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
