# Generated by Django 3.1.6 on 2022-01-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='google_id',
            field=models.CharField(default=0, max_length=50, verbose_name=''),
            preserve_default=False,
        ),
    ]
