# Generated by Django 3.1.6 on 2022-01-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220104_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='google_id',
            field=models.CharField(max_length=50, unique=True, verbose_name=''),
        ),
    ]
