# Generated by Django 3.1.6 on 2022-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220104_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verificated',
        ),
        migrations.AddField(
            model_name='profile',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed setup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Username'),
        ),
    ]
