# Generated by Django 3.1.6 on 2022-03-07 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('personality', '0001_initial'),
        ('users', '0005_auto_20220105_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='completed',
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_artists',
            field=models.ManyToManyField(to='music.Artist', verbose_name='Liked Artists'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_songs',
            field=models.ManyToManyField(to='music.Song', verbose_name='Liked Songs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_persoanlity', to='personality.personality', verbose_name='Personality'),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_history',
            field=models.ManyToManyField(related_name='persoanlity_history', to='personality.Personality', verbose_name='Personality History'),
        ),
        migrations.AddField(
            model_name='profile',
            name='suggested_songs',
            field=models.ManyToManyField(to='music.SuggestedSongs', verbose_name='Suggested Songs'),
        ),
    ]
