# Generated by Django 3.1.6 on 2022-03-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220307_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='personality',
            new_name='current_personality',
        ),
    ]
