# Generated by Django 4.0.4 on 2022-04-28 12:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mind', models.CharField(choices=[('E', 'EXTRAVERTED'), ('I', 'INTROVERTED')], max_length=1, verbose_name='Mind')),
                ('mind_p', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)], verbose_name='Mind percentage')),
                ('energy', models.CharField(choices=[('N', 'INTUITIVE'), ('S', 'OBSERVANT')], max_length=1, verbose_name='Energy')),
                ('energy_p', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)], verbose_name='Energy percentage')),
                ('nature', models.CharField(choices=[('F', 'FEELING'), ('T', 'THINKING')], max_length=1, verbose_name='Nature')),
                ('nature_p', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)], verbose_name='Nature percentage')),
                ('tactics', models.CharField(choices=[('J', 'JUDGING'), ('P', 'Email')], max_length=1, verbose_name='Tactics')),
                ('tactics_p', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)], verbose_name='Tactics percentage')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
            ],
        ),
    ]
